apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: portfolio-backend
  name: portfolio-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: portfolio-backend
    spec:
      containers:
      - image: doll1av/backend:v1.00
        name: backend
        ports:
        - containerPort: 3001
        resources: {}
status: {}