apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: portfolio-frontend
  name: portfolio-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: portfolio-frontend
    spec:
      containers:
      - image: doll1av/frontend:v1.00
        name: frontend
        ports:
        - containerPort: 3000
        resources: {}
status: {}